<?php

namespace AppBundle\Repository;

/**
 * GamePlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamePlayRepository extends \Doctrine\ORM\EntityRepository
{
}
