<?php

namespace AppBundle\Repository;

/**
 * DiceGamePlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiceGamePlayRepository extends \Doctrine\ORM\EntityRepository
{
}
